# Generated by Django 4.0.4 on 2022-05-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='category name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='product name')),
                ('product_count', models.IntegerField(default=1, verbose_name='product count')),
                ('original_price', models.FloatField(verbose_name='original price')),
                ('selling_price', models.FloatField(blank=True, null=True, verbose_name='selling price')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='product code')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
