# Generated by Django 4.0.4 on 2022-05-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options_product_is_delete_soldproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soldproducts',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='soldproducts',
            name='payment_type',
            field=models.CharField(choices=[('KARTA ORQALI', 'Karta orqali'), ('NAQD PUL', 'Naqd pul'), ("ARALASH TO'LOV", "Aralash to'lov")], default='Naqd pul', max_length=100),
        ),
    ]
