# Generated by Django 4.0.4 on 2022-05-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_soldproducts_options_soldproducts_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldproducts',
            old_name='by_count',
            new_name='buy_count',
        ),
        migrations.AddField(
            model_name='soldproducts',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
