# Generated by Django 4.0.4 on 2022-05-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_options_alter_soldproducts_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldproducts',
            old_name='product',
            new_name='product_id',
        ),
    ]
